# services:
#   postgres:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres1
#       POSTGRES_PASSWORD: password1
#     volumes:
#       - 'postgres:/var/lib/postgresql/data'
#     ports:
#       - "5432:5432"
#   postgres_queue:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres1
#       POSTGRES_PASSWORD: password1
#     volumes:
#       - 'postgres_queue:/var/lib/postgresql/data'
#     ports:
#       - "5433:5432"

# volumes:
#   postgres:
#   postgres_queue: