default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  primary:
    <<: *default
    database: teletri_development
    host: <%= ENV.fetch('DB_HOST', 'localhost') %>
    username: <%= ENV.fetch('DB_USER', 'postgres') %>
    password: <%= ENV.fetch('DB_PASSWORD', 'password') %>
    port: <%= ENV.fetch('DB_PORT', 5432) %>
  queue:
    <<: *default
    database: teletri_development_queue
    host: <%= ENV.fetch('QUEUE_DB_HOST', 'localhost') %>
    username: <%= ENV.fetch('QUEUE_DB_USER', 'postgres') %>
    password: <%= ENV.fetch('QUEUE_DB_PASSWORD', 'password') %>
    port: <%= ENV.fetch('QUEUE_DB_PORT', 5433) %>
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: teletri_test
    host: <%= ENV.fetch('DB_HOST', 'localhost') %>
    username: <%= ENV.fetch('DB_USER', 'postgres') %>
    password: <%= ENV.fetch('DB_PASSWORD', 'password') %>
    port: <%= ENV.fetch('DB_PORT', 5432) %>
  queue:
    <<: *default
    database: teletri_test_queue
    host: <%= ENV.fetch('QUEUE_DB_HOST', 'localhost') %>
    username: <%= ENV.fetch('QUEUE_DB_USER', 'postgres') %>
    password: <%= ENV.fetch('QUEUE_DB_PASSWORD', 'password') %>
    port: <%= ENV.fetch('QUEUE_DB_PORT', 5433) %>
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *default
    database: teletri_production_queue
    url: <%= ENV['QUEUE_DATABASE_URL'] %>
    migrations_paths: db/queue_migrate