<% require "dotenv"; Dotenv.load(".env") %>

service: teletri

image: panaet780/teletri

servers:
  web:
    hosts:
      - 82.97.253.158

proxy:
  ssl: true
  host: spree.teletri.ru

registry:
  username: panaet780
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_ENDPOINT
    - AWS_REGION
    - AWS_BUCKET
    - DATABASE_URL
    - QUEUE_DATABASE_URL
    - CABLE_DATABASE_URL
    - CACHE_DATABASE_URL
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_LOG_LEVEL: debug

aliases:
  console: app exec --interactive --reuse 'bin/rails console'
  shell: app exec --interactive --reuse 'bash'
  logs: app logs -f
  dbc: app exec --interactive --reuse 'bin/rails dbconsole'

volumes:
  - 'teletri_storage:/rails/storage'

asset_path: /rails/public/assets

builder:
  arch: amd64
  args:
    RUBY_VERSION: 3.3.0

accessories:
  postgres:
    image: postgres:15
    host: 82.97.253.158
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: teletri_production
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data