test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

timeweb:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:timeweb, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:timeweb, :secret_access_key) %>
  endpoint: "https://s3.timeweb.cloud"
  region: "ru-1"
  bucket: "ae4cd7ee-b62e0601-19d6-483e-bbf1-416b386e5c23"