local:
  service: Disk
  root: <%= Rails.root.join("public/storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

production:
  service: Disk
  root: <%= Rails.root.join("public/storage") %>

amazon:
  service: S3
  access_key_id: ""
  secret_access_key: ""
  bucket: ""
  region: "" # e.g. 'us-east-1'
