# Editor TinyMCE Configuration

# range of configuration options then please go here:
#
#    http://www.tinymce.com/wiki.php/configuration

# TinyMCE Options
mode: "exact"
language: "<%= I18n.locale.to_s.split('-')[0].downcase %>"
schema: "html5-strict"
element_format: "html"
menubar: false
statusbar: false

toolbar:
  - styleselect | bold italic underline strikethrough | undo redo | bullist numlist
  - alignleft aligncenter alignright alignjustify | image link code charmap media
plugins:
  - image
  - link
  - code
  - media
  - table
  - directionality
  - wordcount
  - lists
